### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by EWTHeckman** [vdelachaux/4DPop-Family#3]
The included 4DPop.htm file has clearly not been updated to match the significant changes to 4D Pop. It still describes the method of activating using the call:

> **EXECUTE METHOD**("4DPop_Palette")

That no longer works.

I'm so far behind the curve on ORDA and object oriented programming that I have no idea how to use the cs.pop (or whatever it is) to make it work. Please update this documentation!

**Comment by vdelachaux** [comment]
Thanks for the feedback, the documentation hasn't been updated yet, it's a long job... and I'm going to devote myself to it asap.

To make 4DPop automatically launched, just activate the property **Execute "On Host Database Event" method of the components**.

![Screenshot 2](https://github.com/vdelachaux/4DPop-Family/assets/623020/b3bfae47-cbd8-47c5-b076-a0d31bd6708f)
